### PR TITLE
Re-make build system + add CI + fix showstopper bugs (fixes #1)

### LINKED ISSUE #1: Build system incomplete? How to build?
Hi!

From a quick look my impression is that the current build system at `src/CMakeLists.txt` is incomplete, e.g. because:
- there is no call to `project(..)`
- there is no call to `cmake_minimum_required(..)`
- there is no call finding `libvisual::libvisual` to make the target available
- the `if(NOT ENABLE_LIBVISUAL)` bypasses most of the build system by default

How do you currently build projectM_libvisual?

I see partial CMake removal commits b79b98a03f5fbaa6366fe9d1e333d3dd466c4cf6 and 000b4375013c3db9f207cee596c152ab08b8c3e1 but they don#t explain themselves to me. What was the idea?

I'm happy to provide pull request but I first need to understand status quo better. Thanks!

Best, Sebastian

### PR DESCRIPTION
**Pull request by hartwork**
Hi! :wave: 

This was encouraged by @revmischa at https://github.com/projectM-visualizer/frontend-libvisual-plug-in/issues/1#issuecomment-1412822201.

From a bird's eye view this pull request does three main things:
- Re-makes the CMake build system to allow standalone compilation against external projectM and libvisual 0.4
- Adds CI based on GitHub Actions
- Fixes three showstopper bugs: stop calling `projectM_resetGL` every single frame, fix keyboard handling, and fix new/delete mis-matches

I should note that:
- (I found the code in here to be identical to https://github.com/projectM-visualizer/projectm/commit/bed864b1e711f241f63eb3b8fc8e7bbd113cf79a right before its removal.)
- I set version "2.1.0" in the build system initially, because to the distro world outside projectM that code (minus the spelling fix) was [packaged as 2.1.0 in distros](https://repology.org/project/libvisual-projectm/versions).
- I'm passing name "libvisual-projectm" to `project(..)` because that is [what distros settled on](https://repology.org/project/libvisual-projectm/versions) in practice.

I'm looking forward to your feedback!

---
Fixes #1

CC @kaixiong

### CODE REVIEW

**Comment by hartwork** [comment]
@kblaschke @revmischa what do you think?

**Comment by revmischa** [comment]
Thanks for your contributions!

**Comment by hartwork** [comment]
@revmischa great to have this merged, thank you!
Is there a chance you could tag the latest `master` (2f504a27ce51cf280d61ef7240f52bb31471d37a) as "2.1.1" or "v2.1.1" in Git? It would allow me to cleanly bump the package to version 2.1.1 in Gentoo Linux.

**Comment by revmischa** [comment]
Done

**Comment by hartwork** [comment]
@revmischa thanks! :+1:

Bumped to 2.1.1 in Gentoo now (https://github.com/gentoo/gentoo/commit/3de0f1463c034846b72d27838195a79ecb52a5db).

**Pull request merged**
